
# Phase 1 Conf

# # pull official base image
# FROM python:3.11.4-slim-buster

# # set work directory
# WORKDIR /usr/src/app

# # set environment variables

# # Prevents Python from writing pyc files to disc
# ENV PYTHONDONTWRITEBYTECODE 1
# # Prevents Python from buffering stdout and stderr
# ENV PYTHONUNBUFFERED 1

# # install dependencies
# RUN pip install --upgrade pip
# COPY ./requirements.txt .
# RUN pip install -r requirements.txt

# # copy project
# COPY . .



# pull official base image
# FROM python:3.11.4-slim-buster
FROM python:3.11.4-slim-bullseye

# set work directory
WORKDIR /usr/src/app

# set environment variables

# Prevents Python from writing pyc files to disc
ENV PYTHONDONTWRITEBYTECODE 1
# Prevents Python from buffering stdout and stderr
ENV PYTHONUNBUFFERED 1

# install system dependencies
# RUN apt-get update && apt-get install -y netcat
RUN apt-get update && apt-get install -y netcat-traditional

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# copy entrypoint.sh
COPY ./entrypoint.sh .
RUN sed -i 's/\r$//g' /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

# copy project
COPY . .

# run entrypoint.sh
ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
