# version: '3.8'

# services:
#   web:
#     build: ./app
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - ./app/:/usr/src/app/
#     ports:
#       - 8000:8000
#     env_file:
#       - ./.env.dev


# add a new service called db
version: '3.8'

services:
  web:
    build: ./app
    # Django's built-in server in development
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      # Create or use a volume named postgres_data, and mount it inside the container at /var/lib/postgresql/data.
      - postgres_data:/var/lib/postgresql/data/
    environment:
      # The only variable required is POSTGRES_PASSWORD, the rest are optional.
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data:
